## --------------------------------------------------------

# 03_real_world_data_to_tensors
### a, b, c, d, j, k, l, m, n

#### 2022161136 - 이재환 (전자공학과)

## --------------------------------------------------------

# a_2d_image_data

In [43]:
import os
import imageio.v2 as imageio
import torch

In [44]:
# image load
img_arr = imageio.imread(os.path.join(os.path.pardir,  "_00_data", "a_image-dog", "bobby.jpg"))

In [45]:
print(type(img_arr)) 
print(img_arr.shape)
print(img_arr.dtype)

# >>
# <class 'numpy.ndarray'> >> imageio.imread를 통해 이미지를 numpy 배열로 가져옴.
# (720, 1280, 3) >> (Height, Width, Channel)
# uint8 >> (0~255)

<class 'numpy.ndarray'>
(720, 1280, 3)
uint8


In [46]:
img = torch.from_numpy(img_arr) # >> numpy배열을 tensor(torch)로 변환
out = img.permute(2,0,1) # >> tensor(pytorch)는 (C, H, W)형태를 사용하기에 permute함수를 통해 바꿔줌 (H, W, C) -> (C, H, W)
print(out.shape) # >> torch.Size([C, H, W])

torch.Size([3, 720, 1280])


In [47]:
data_dir = os.path.join(os.path.pardir,  "_00_data", "b_image-cats")
filenames = [
    name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png'
] # >> .png형식의 파일만 선별하여 리스트에 저장함.
print(filenames)

['cat1.png', 'cat2.png', 'cat3.png']


In [48]:
from PIL import Image

In [49]:
for i, filename in enumerate(filenames):
    image = Image.open(os.path.join(data_dir, filename))
    image.show()
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    print(img_arr.shape)
    print(img_arr.dtype)
# >>
# (256, 256, 3)
# uint8
# (256, 256, 3)
# uint8
# (256, 256, 3)
# uint8

(256, 256, 3)
uint8
(256, 256, 3)
uint8
(256, 256, 3)
uint8


In [50]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype = torch.uint8)

In [51]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2,0,1)
    batch[i] = img_t

print(batch.shape) # >> 검출된 cat사진의 shape는 [3,3,256,256]. 

torch.Size([3, 3, 256, 256])


In [52]:
batch = batch.float()
batch /= 255.0
print(batch.dtype)
print(batch.shape)

torch.float32
torch.Size([3, 3, 256, 256])


In [53]:
n_channels = batch.shape[1]

for c in range(n_channels):
    mean = torch.mean(batch[:,c])
    std = torch.std(batch[:,c])
    print(mean, std)
    batch[:,c] = (batch[:, c] - mean) / std

tensor(0.5799) tensor(0.2212)
tensor(0.4493) tensor(0.2068)
tensor(0.3554) tensor(0.1931)


## --------------------------------------------------------

# b_tabular_wine_data

In [54]:
import csv
import os
import numpy as np

In [55]:
wine_path = os.path.join(os.path.pardir, "_00_data", "d_tabular-wine", "winequality-white.csv")
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
print(wineq_numpy.dtype)
print(wineq_numpy.shape)
print(wineq_numpy)
print()
# >>
# float32
# (4898, 12)
# [[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
#  [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
#  [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
#  ...
#  [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
#  [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
#  [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]

float32
(4898, 12)
[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]



In [56]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
print(col_list)
print()
# >>
# ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']



In [57]:
import torch

In [58]:
wineq = torch.from_numpy(wineq_numpy)
print(wineq.dtype)
print(wineq.shape)
print()
# >>
# torch.float32
# torch.Size([4898, 12])

torch.float32
torch.Size([4898, 12])



In [59]:
data = wineq[:, :-1] # Selects all rows and all columns except the last
print(data.dtype)
print(data.shape)
print(data)
print()
# >>
# torch.float32
# torch.Size([4898, 11])
# tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
#         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
#         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
#         ...,
#         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
#         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
#         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])


torch.float32
torch.Size([4898, 11])
tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
        [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])



In [60]:
target = wineq[:, -1] # Select all rows and the last column
print(target.dtype)
print(target.shape)
print(target)
print()
# >>
# torch.float32
# torch.Size([4898])
# tensor([6., 6., 6.,  ..., 6., 7., 6.])

torch.float32
torch.Size([4898])
tensor([6., 6., 6.,  ..., 6., 7., 6.])



In [61]:
target = target.to(torch.int64) # treat labels as an integer
print(target.dtype)
print(target.shape)
print(target)
print()
# >>
# torch.int64
# torch.Size([4898])
# tensor([6, 6, 6,  ..., 6, 7, 6])

torch.int64
torch.Size([4898])
tensor([6, 6, 6,  ..., 6, 7, 6])



In [62]:
eye_matrix = torch.eye(10)
# We can use 'target' tensor as indices to extrack the corresponding rows from the identity matrix
# It can generate the one-hot vectors for each element in the 'target' tensor
onehot_target = eye_matrix[target]

print(onehot_target.shape) # >>> torch.Size([4898, 10])
print(onehot_target[0])
print(onehot_target[1])
print(onehot_target[-2])
print(onehot_target)

torch.Size([4898, 10])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [63]:
data_mean = torch.mean(data, dim=0)
data_var = torch.var(data, dim=0)
data = (data - data_mean) / torch.sqrt(data_var)
print(data)
# >>
# tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
#          -3.4915e-01, -1.3930e+00],
#         [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
#           1.3418e-03, -8.2419e-01],
#         [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
#          -4.3677e-01, -3.3663e-01],
#         ...,
#         [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
#          -2.6153e-01, -9.0545e-01],
#         [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
#          -9.6251e-01,  1.8574e+00],
#         [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
#          -1.4882e+00,  1.0448e+00]])

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])


In [64]:
from sklearn.model_selection import train_test_split

In [65]:
X_train, X_test, y_train, y_test = train_test_split(data, onehot_target, test_size=0.2)

In [66]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)
# >>
# torch.Size([3918, 11])
# torch.Size([3918, 10])
# torch.Size([980, 11])
# torch.Size([980, 10])

torch.Size([3918, 11])
torch.Size([3918, 10])
torch.Size([980, 11])
torch.Size([980, 10])


In [67]:
def get_wine_data():
    wine_path = os.path.join(os.path.pardir, "_00_data", "d_tabular-wine", "winequality-white.csv")
    wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)

    wineq = torch.from_numpy(wineq_numpy)

    data = wineq[:, :-1] # Select all rows and all columns except the last
    target = wineq[:, -1].to(torch.int64) # treat labels as an integer

    eye_matrix = torch.eye(10)
    onehot_target = eye_matrix[target]

    data_mean = torch.mean(data, dim=0)
    data_var = torch.var(data, dim=0)
    data = (data - data_mean) / torch.sqrt(data_var)

    X_train, X_valid, y_train, y_valid = train_test_split(data, onehot_target, test_size = 0.2)

    return X_train, X_valid, y_train, y_valid

In [68]:
# get_wind_data()를 호출해 검출된 데이터 샘플, label(one-hot)을 확인해봄.
if __name__ == "__main__":
    
    X_train, X_valid, y_train, y_valid = get_wine_data()

    print("X_train:", X_train.shape, X_train.dtype)
    print("y_train:", y_train.shape, y_train.dtype)
    print("X_valid:", X_valid.shape, X_valid.dtype)
    print("y_valid:", y_valid.shape, y_valid.dtype)

    print("\nFirst trained data sample :")
    print(X_train[0])

    print("\nFirst trained data label(one-hot) :")
    print(y_train[0])

X_train: torch.Size([3918, 11]) torch.float32
y_train: torch.Size([3918, 10]) torch.float32
X_valid: torch.Size([980, 11]) torch.float32
y_valid: torch.Size([980, 10]) torch.float32

First trained data sample :
tensor([ 1.2386, -0.9747, -0.0346, -1.0235, -0.5846, -0.9001, -1.5615, -0.6110,
        -0.4521, -0.9625, -0.0116])

First trained data label(one-hot) :
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])


## --------------------------------------------------------

# c_taular_california_housing

In [10]:
# https://medium.com/analytics-vidhya/implement-linear-regression-on-boston-housing-dataset-by-pytorch-c5d29546f938
# https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset
import torch
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
print(housing.keys())

print(type(housing.data))
print(housing.data.dtype)
print(housing.data.shape)
print(housing.feature_names)

print(housing.target.shape)
print(housing.target_names)

# >>

# dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])
# <class 'numpy.ndarray'>
# float64
# (20640, 8)
# ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
# (20640,)
# ['MedHouseVal']

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])
<class 'numpy.ndarray'>
float64
(20640, 8)
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
(20640,)
['MedHouseVal']


In [11]:
import numpy as np

In [12]:
print(housing.data.min(), housing.data.max())

-124.35 35682.0


In [13]:
data_mean = np.mean(housing.data, axis = 0)
data_var = np.var(housing.data, axis = 0)
data = (housing.data - data_mean) / np.sqrt(data_var)
target = housing.target

print(data.min(), data.max())

-2.3859923416733877 119.41910318829314


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

In [16]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [17]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

torch.Size([16512, 8])
torch.Size([16512])
torch.Size([4128, 8])
torch.Size([4128])


## --------------------------------------------------------

# d_bikes_sharing_data

In [2]:
import os
import numpy as np
import torch

In [3]:
torch.set_printoptions(edgeitems=2, threshold=50, linewidth=75)

In [4]:
bikes_path = os.path.join(os.path.pardir, "_00_data", "e_time-series-bike-sharing-dataset", "hour-fixed.csv")

In [5]:
bikes_numpy = np.loadtxt(
    fname=bikes_path, dtype=np.float32, delimiter=",", skiprows=1,
    converters={
        1: lambda x: float(x[8:10]) # 2011-01-07 --> 07 --> 7.0
    }
)
bikes = torch.from_numpy(bikes_numpy).to(torch.float)
print(bikes.shape) # >> torch.Size([17520, 17])

torch.Size([17520, 17])


In [6]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
print(daily_bikes.shape) # >> torch.Size([730, 24, 17])

torch.Size([730, 24, 17])


In [7]:
daily_bikes_data = daily_bikes[:, :, :-1]
daily_bikes_target = daily_bikes[:,:,-1].unsqueeze(dim=-1)

In [8]:
print(daily_bikes_data.shape)
print(daily_bikes_target.shape)
# >>
# torch.Size([730, 24, 16])
# torch.Size([730, 24, 1])

torch.Size([730, 24, 16])
torch.Size([730, 24, 1])


In [9]:
first_day_data = daily_bikes_data[0]
print(first_day_data.shape)

torch.Size([24, 16])


In [10]:
# Whether situation: 1: clear, 2:mist, 3: light rain/snow, 4: heavy rain/snow
print(first_day_data[:, 9])
print(first_day_data[:,9].shape, first_day_data[:,9].dtype)
eye_matrix = torch.eye(4)
print(eye_matrix)
# >>

# tensor([1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
#         2., 3., 3., 2., 2., 2., 2.])
# torch.Size([24]) torch.float32
# tensor([[1., 0., 0., 0.],
#         [0., 1., 0., 0.],
#         [0., 0., 1., 0.],
#         [0., 0., 0., 1.]])

tensor([1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
        2., 3., 3., 2., 2., 2., 2.])
torch.Size([24]) torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [11]:
weather_onehot = eye_matrix[first_day_data[:, 9].to(torch.int64) - 1]
print(weather_onehot.shape)
print(weather_onehot)
# >>
# torch.Size([24, 4])
# tensor([[1., 0., 0., 0.],
#         [1., 0., 0., 0.],
#         ...,
#         [0., 1., 0., 0.],
#         [0., 1., 0., 0.]])

torch.Size([24, 4])
tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])


In [12]:
first_day_data_torch = torch.cat(tensors=(first_day_data, weather_onehot), dim=1)
print(first_day_data_torch.shape)
print(first_day_data_torch)

# >>

# torch.Size([24, 20])
# tensor([[ 1.,  1.,  ...,  0.,  0.],
#         [ 2.,  1.,  ...,  0.,  0.],
#         ...,
#         [23.,  1.,  ...,  0.,  0.],
#         [24.,  1.,  ...,  0.,  0.]])

torch.Size([24, 20])
tensor([[ 1.,  1.,  ...,  0.,  0.],
        [ 2.,  1.,  ...,  0.,  0.],
        ...,
        [23.,  1.,  ...,  0.,  0.],
        [24.,  1.,  ...,  0.,  0.]])


In [13]:
day_data_torch_list = []

for daily_idx in range(daily_bikes_data.shape[0]):  # range(730)
  day = daily_bikes_data[daily_idx]  # day.shape: [24, 16]
  weather_onehot = eye_matrix[day[:, 9].to(torch.int64) - 1]
  day_data_torch = torch.cat(tensors=(day, weather_onehot), dim=1)  # day_data_torch.shape: [24, 20]
  day_data_torch_list.append(day_data_torch)

print(len(day_data_torch_list))
daily_bikes_data = torch.stack(day_data_torch_list, dim=0)
print(daily_bikes_data.shape) # >> torch.Size([730, 24, 20])

730
torch.Size([730, 24, 20])


In [14]:
print(daily_bikes_data[:,:,:9].shape, daily_bikes_data[:,:,10:].shape) # >> torch.Size([730, 24, 9]) torch.Size([730, 24, 14])
daily_bikes_data = torch.cat(
    [daily_bikes_data[:,:,1:9], daily_bikes_data[:,:,10:]], dim=2
) # Drop 'instant' and 'whethersit' columns
print(daily_bikes_data.shape) # >> torch.Size([730, 24, 20])

torch.Size([730, 24, 9]) torch.Size([730, 24, 10])
torch.Size([730, 24, 18])


In [15]:
temperatures = daily_bikes_data[:,:,8]
daily_bikes_data[:,:,8]= (daily_bikes_data[:,:,8] - torch.mean(temperatures)) / torch.std(temperatures)

In [18]:
# for checking data
print(temperatures)
print(daily_bikes_data)

tensor([[-1.3213, -1.4248,  ..., -0.4932, -0.1827],
        [-0.1827, -0.2862,  ..., -1.3213, -1.4248],
        ...,
        [-1.2178, -1.2178,  ..., -1.5284, -1.5284],
        [-1.6319, -1.6319,  ..., -1.2178, -1.2178]])
tensor([[[ 1.,  1.,  ...,  0.,  0.],
         [ 1.,  1.,  ...,  0.,  0.],
         ...,
         [ 1.,  1.,  ...,  0.,  0.],
         [ 1.,  1.,  ...,  0.,  0.]],

        [[ 2.,  1.,  ...,  0.,  0.],
         [ 2.,  1.,  ...,  0.,  0.],
         ...,
         [ 2.,  1.,  ...,  0.,  0.],
         [ 2.,  1.,  ...,  0.,  0.]],

        ...,

        [[30.,  1.,  ...,  0.,  0.],
         [30.,  1.,  ...,  0.,  0.],
         ...,
         [30.,  1.,  ...,  0.,  0.],
         [30.,  1.,  ...,  0.,  0.]],

        [[31.,  1.,  ...,  0.,  0.],
         [31.,  1.,  ...,  0.,  0.],
         ...,
         [31.,  1.,  ...,  0.,  0.],
         [31.,  1.,  ...,  0.,  0.]]])


## --------------------------------------------------------

# j_linear_regression_dataset_dataloader

In [21]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split

In [23]:
class LinearRegressionDataset(Dataset):
    def __init__(self, N=50, m=-3, b=2, *args, **kwargs):
        # N: number of samples, e.g. 50
        # m: slope
        # b: offset
        super().__init__(*args, **kwargs)

        self.x = torch.rand(N, 2)
        self.noise = torch.rand(N) * 0.2
        self.m = m
        self.b = b
        self.y = (torch.sum(self.x * self.m) + self.b + self.noise).unsqueeze(-1)

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

    def __str__(self):
        str = "Data Size : {0}, Input Shape : {1}, Target Shape : {2}".format(
            len(self.x), self.x.shape, self.y.shape
        )
        return str

In [27]:
if __name__ == "__main__":
    linear_regression_dataset = LinearRegressionDataset()

    print(linear_regression_dataset)

    print("#" * 70, 1)

    for idx, sample in enumerate(linear_regression_dataset):
        input, target = sample
        print("{0} - {1} : {2}".format(idx, input, target))

    train_dataset, validation_dataset, test_dataset = random_split(linear_regression_dataset, [0.7, 0.2, 0.1])

    print("#" * 70, 2)

    print(len(train_dataset), len(validation_dataset), len(test_dataset))

    print("#" * 70, 3)

    train_data_loader = DataLoader(
        dataset=train_dataset,
        batch_size=4,
        shuffle=True
    )

    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        print("{0} - {1} : {2}".format(idx, input, target))

    

Data Size : 50, Input Shape : torch.Size([50, 2]), Target Shape : torch.Size([50, 1])
###################################################################### 1
0 - tensor([0.5961, 0.9314]) : tensor([-155.1123])
1 - tensor([0.4501, 0.2212]) : tensor([-155.0811])
2 - tensor([0.2118, 0.9063]) : tensor([-155.1235])
3 - tensor([0.8032, 0.3683]) : tensor([-155.0403])
4 - tensor([0.0747, 0.3851]) : tensor([-155.0423])
5 - tensor([0.9147, 0.5950]) : tensor([-155.0902])
6 - tensor([0.8680, 0.8319]) : tensor([-154.9733])
7 - tensor([0.3940, 0.8024]) : tensor([-155.1250])
8 - tensor([0.8041, 0.2023]) : tensor([-155.0080])
9 - tensor([0.0211, 0.9159]) : tensor([-155.0431])
10 - tensor([0.4925, 0.0199]) : tensor([-155.0009])
11 - tensor([0.7793, 0.9869]) : tensor([-154.9866])
12 - tensor([0.9804, 0.3146]) : tensor([-155.0848])
13 - tensor([0.2436, 0.2819]) : tensor([-154.9791])
14 - tensor([0.7760, 0.8489]) : tensor([-155.1323])
15 - tensor([0.3210, 0.9142]) : tensor([-155.0014])
16 - tensor([0.7458

## --------------------------------------------------------

# k_2d_image_dataset_dataloader

In [43]:
import os
import torch
from PIL import Image
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms

In [44]:
class DogCat2DImageDataset(Dataset):
    def __init__(self):
        self.image_transforms = transforms.Compose([
            transforms.Resize(size=(256,256)),
            transforms.ToTensor()
        ])
        # 인식이 안되어서 하드코딩진행하였음.
        # dogs_dir = os.path.join(os.path.pardir,"__00_data", "a_image-dog")
        # cats_dir = os.path.join(os.path.pardir,"__00_data", "b_image-cats")

        image_lst = [
            Image.open(os.path.join(os.path.pardir,  "_00_data", "a_image-dog", "bobby.jpg")), # (1280, 720, 3)
            Image.open(os.path.join(os.path.pardir,  "_00_data", "b_image-cats", "cat1.png")), # (256, 256, 3)
            Image.open(os.path.join(os.path.pardir,  "_00_data", "b_image-cats", "cat2.png")), # (256, 256, 3)
            Image.open(os.path.join(os.path.pardir,  "_00_data", "b_image-cats", "cat3.png")), # (256, 256, 3)
        ]

        image_lst = [self.image_transforms(img) for img in image_lst]
        self.images = torch.stack(image_lst, dim=0)

        # 0 : "dog", 1: "cat"
        self.image_labels = torch.tensor([[0], [1], [1], [1]])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        return self.images[idx], self.image_labels[idx]

    def __str__(self):
        str = "Data Size: {0}, Input Shape : {1}, Target Shape : {2}".format(
            len(self.images), self.images.shape, self.image_labels.shape
        )
        return str

In [45]:
if __name__ == "__main__":
    dog_cat_2d_image_dataset = DogCat2DImageDataset()

    print(dog_cat_2d_image_dataset)

    print("#" * 70 , 1)

    for idx, sample in enumerate(dog_cat_2d_image_dataset):
        input, target = sample
        print("{0} - {1} : {2}".format(idx, input.shape, target))

    train_dataset, test_dataset = random_split(dog_cat_2d_image_dataset, [0.7, 0.3])

    print("#" * 70, 2)

    print(len(train_dataset), len(test_dataset))

    print("#" * 70, 3)

    train_data_loader = DataLoader(
        dataset=train_dataset,
        batch_size=2,
        shuffle=True
    )

    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        print("{0} - {1} : {2}".format(idx, input.shape, target))

Data Size: 4, Input Shape : torch.Size([4, 3, 256, 256]), Target Shape : torch.Size([4, 1])
###################################################################### 1
0 - torch.Size([3, 256, 256]) : tensor([0])
1 - torch.Size([3, 256, 256]) : tensor([1])
2 - torch.Size([3, 256, 256]) : tensor([1])
3 - torch.Size([3, 256, 256]) : tensor([1])
###################################################################### 2
3 1
###################################################################### 3
0 - torch.Size([2, 3, 256, 256]) : tensor([[1],
        [1]])
1 - torch.Size([1, 3, 256, 256]) : tensor([[1]])


## --------------------------------------------------------

# l_wine_dataset_dataloader

In [46]:
import os
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

In [50]:
class WineDataset(Dataset):
    def __init__(self):
        wine_path = os.path.join(os.path.pardir, "_00_data", "d_tabular-wine", "winequality-white.csv")
        wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
        wineq = torch.from_numpy(wineq_numpy)

        data = wineq[:, :-1] # Selects all rows and columns except the last
        data_mean = torch.mean(data, dim=0)
        data_var = torch.var(data, dim=0)
        self.data = (data - data_mean) / torch.sqrt(data_var)

        target = wineq[:, -1].to(torch.int64) # treat labels as an integer
        eye_matrix = torch.eye(10)
        self.target = eye_matrix[target]

        assert len(self.data) == len(self.target)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        wine_feature = self.data[idx]
        wine_target = self.target[idx]
        return wine_feature, wine_target

    def __str__(self):
        str = "Data Size: {0}, Input : {1}, Target Shape : {2}".format(
            len(self.data), self.data.shape, self.target.shape
        )
        return str

In [54]:
if __name__ == "__main__":
    wine_dataset = WineDataset()

    print(wine_dataset)

    print("#" * 70, 1)

    for idx, sample in enumerate(wine_dataset):
        input, target = sample
        #print("{0} - {1}: {2}".format(idx, input.shape, target.shape)) index가 많은 관계로 확인후 주석처리.

    train_dataset, validation_dataset, test_dataset = random_split(wine_dataset, [0.7, 0.2, 0.1])

    print("#" * 70, 2)

    print(len(train_dataset), len(validation_dataset), len(test_dataset)) # >> 3429, 980, 489

    print("#" * 70, 3)

    train_data_loader = DataLoader(
        dataset=train_dataset,
        batch_size = 32,
        shuffle=True,
        drop_last=True
    )

    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

Data Size: 4898, Input : torch.Size([4898, 11]), Target Shape : torch.Size([4898, 10])
###################################################################### 1
###################################################################### 2
3429 980 489
###################################################################### 3
0 - torch.Size([32, 11]): torch.Size([32, 10])
1 - torch.Size([32, 11]): torch.Size([32, 10])
2 - torch.Size([32, 11]): torch.Size([32, 10])
3 - torch.Size([32, 11]): torch.Size([32, 10])
4 - torch.Size([32, 11]): torch.Size([32, 10])
5 - torch.Size([32, 11]): torch.Size([32, 10])
6 - torch.Size([32, 11]): torch.Size([32, 10])
7 - torch.Size([32, 11]): torch.Size([32, 10])
8 - torch.Size([32, 11]): torch.Size([32, 10])
9 - torch.Size([32, 11]): torch.Size([32, 10])
10 - torch.Size([32, 11]): torch.Size([32, 10])
11 - torch.Size([32, 11]): torch.Size([32, 10])
12 - torch.Size([32, 11]): torch.Size([32, 10])
13 - torch.Size([32, 11]): torch.Size([32, 10])
14 - torch.Size([32

## --------------------------------------------------------

# m_california_housing_data_dataloader

In [55]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

In [64]:
class CaliforniaHousingDataset(Dataset):
    def __init__(self):
        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()
        data_mean = np.mean(housing.data, axis=0)
        data_var = np.var(housing.data, axis=0)
        self.data = torch.tensor((housing.data - data_mean)/ np.sqrt(data_var), dtype=torch.float32)
        self.target = torch.tensor(housing.target, dtype=torch.float32)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample_data = self.data[idx]
        sample_target = self.target[idx]
        return sample_data, sample_target

    def __str__(self):
        str = "Data Size: {0}, Input Shape: {1}, Target Shape: {2}".format(
            len(self.data), self.data.shape, self.target.shape
        )
        return str

In [68]:
if __name__ == "__main__":
    california_housing_dataset = CaliforniaHousingDataset()

    print(california_housing_dataset)

    print("#" * 70, 1)

    for idx, sample in enumerate(california_housing_dataset):
        input, target = sample
        #print("{0} - {1}: {2}".format(idx, input.shape, target.shape)) >> 인덱스의 양이 20649개임을 확인 후 주석처리하여 보기 쉽게함.

    train_dataset, validation_dataset, test_dataset = random_split(california_housing_dataset, [0.7, 0.2, 0.1])

    print("#" * 70, 2)

    print(len(train_dataset), len(validation_dataset), len(test_dataset))

    print("#" * 70, 3)

    train_data_loader = DataLoader(
        dataset=train_dataset,
        batch_size = 32,
        shuffle = True,
        drop_last=True # >> 마지막 batch는 drop함.
    )

    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        # print("{0} - {1}: {2}".format(idx, input.shape, target.shape)) >> Index : 450 - torch.Size([32, 8]): torch.Size([32])
        

Data Size: 20640, Input Shape: torch.Size([20640, 8]), Target Shape: torch.Size([20640])
###################################################################### 1
###################################################################### 2
14448 4128 2064
###################################################################### 3


## --------------------------------------------------------

# n_time_seris_dataset_dataloader

In [16]:
import os
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

#BASE_PATH = str(Path(__file__).resolve().parent.parent.parent) # NameError: name '__file__' is not defined
BASE_PATH = str(Path.cwd().parent) #__file__가 정의되지 않았다고 오류 문구가 뜨기에 수정함.
import sys
sys.path.append(BASE_PATH)

In [31]:
class BikesDataset(Dataset):
    def __init__(self, train=True, test_days=1):
        self.train = train
        self.test_days = test_days

        bikes_path = os.path.join(BASE_PATH, "_00_data", "e_time-series-bike-sharing-dataset", "hour-fixed.csv")

        bikes_numpy = np.loadtxt(
            fname=bikes_path, dtype=np.float32, delimiter=",", skiprows=1,
            converters={
                1: lambda x: float(x[8:10]) # 2011-01-07 --> 07 --> 7
            }
        )
        bikes = torch.from_numpy(bikes_numpy)

        daily_bikes = bikes.view(-1, 24, bikes.shape[1]) # daily_bikes.shape: torch.Size([730, 24, 17])
        self.daily_bikes_target = daily_bikes[:,:,-1].unsqueeze(dim=-1)

        self.daily_bikes_data = daily_bikes[:, :, :-1]
        eye_matrix = torch.eye(4)

        day_data_torch_list = []
        for daily_idx in range(self.daily_bikes_data.shape[0]): # range(730)
            day = self.daily_bikes_data[daily_idx] # day.shape: [24, 17]
            weather_onehot = eye_matrix[day[:, 9].to(torch.int64) - 1]
            day_data_torch = torch.cat(tensors=(day, weather_onehot), dim=1) # day_torch.shape : [24, 21]
            day_data_torch_list.append(day_data_torch)

        self.daily_bikes_data = torch.stack(day_data_torch_list, dim=0)

        self.daily_bikes_data = torch.cat(
            [self.daily_bikes_data[:, :, :9], self.daily_bikes_data[:, :, 10:]], dim=2
        )

        total_length = len(self.daily_bikes_data)
        self.train_bikes_data = self.daily_bikes_data[:total_length - test_days]
        self.train_bikes_targets = self.daily_bikes_target[:total_length - test_days]
        train_temperatures = self.train_bikes_data[:, :, 9]
        train_temperatures_mean = torch.mean(train_temperatures)
        train_temperatures_std = torch.std(train_temperatures)
        self.train_bikes_data[:, :, 9] = (self.train_bikes_data[:, :, 9] - train_temperatures_mean) / train_temperatures_std

        assert len(self.train_bikes_data) == len(self.train_bikes_targets)

        self.test_bikes_data = self.daily_bikes_data[-test_days:]
        self.test_bikes_targets = self.daily_bikes_target[-test_days:]

        self.test_bikes_data[:, :, 9] = (self.test_bikes_data[:, :, 9] - train_temperatures_mean) / train_temperatures_std

        assert len(self.test_bikes_data) == len(self.test_bikes_targets)

    def __len__(self):
        return len(self.train_bikes_data) if self.train is True else len(self.test_bikes_data)

    def __getitem__(self, idx):
        bike_feature = self.train_bikes_data[idx] if self.train is True else self.test_bikes_data[idx]
        bike_target = self.train_bikes_targets[idx] if self.train is True else self.test_bikes_targets[idx]
        return bike_feature, bike_target
        
    def __str__(self):
        if self.train is True:
            str = "Data Size : {0}, Input Shape : {1}, Target Shape : {2}".format(
                len(self.train_bikes_data), self.train_bikes_data.shape, self.train_bikes_targets.shape
            )
        else:
            str = "Data Size : {0}, Input Shape : {1}, Target Shape : {2}".format(
                len(self.test_bikes_data), self.test_bikes_data.shape, self.test_bikes_targets.shape
            )            
        return str

In [32]:
if __name__ == "__main__":
    train_bikes_dataset = BikesDataset(train=True, test_days=1)
    print(train_bikes_dataset)

    print("#" * 70, 1)

    train_dataset, validation_dataset = random_split(train_bikes_dataset, [0.8, 0.2])

    print("[TRAIN]")
    for idx, sample in enumerate(train_dataset):
        input, target = sample
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

    train_data_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True, drop_last = True)

    for idx, batch in enumerate(train_data_loader):
        input, target = batch
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

    print("#" * 70, 2)

    print("[VALIDATION]")
    for idx, sample in enumerate(validation_dataset):
        input, target = sample
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

    validation_data_loader = DataLoader(dataset=validation_dataset, batch_size=32)

    for idx, batch in enumerate(validation_data_loader):
        input, target = batch
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

    print("#" * 70, 3)

    test_dataset = BikesDataset(train=False, test_days = 1)
    print(test_dataset)

    print("[TEST]")
    for idx, sample in enumerate(test_dataset):
        input, target = sample
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))

    test_data_loader = DataLoader(dataset=test_dataset, batch_size = len(test_dataset))

    for idx, batch in enumerate(test_data_loader):
        input, target = batch
        print("{0} - {1}: {2}".format(idx, input.shape, target.shape))
    

Data Size : 729, Input Shape : torch.Size([729, 24, 19]), Target Shape : torch.Size([729, 24, 1])
###################################################################### 1
[TRAIN]
0 - torch.Size([24, 19]): torch.Size([24, 1])
1 - torch.Size([24, 19]): torch.Size([24, 1])
2 - torch.Size([24, 19]): torch.Size([24, 1])
3 - torch.Size([24, 19]): torch.Size([24, 1])
4 - torch.Size([24, 19]): torch.Size([24, 1])
5 - torch.Size([24, 19]): torch.Size([24, 1])
6 - torch.Size([24, 19]): torch.Size([24, 1])
7 - torch.Size([24, 19]): torch.Size([24, 1])
8 - torch.Size([24, 19]): torch.Size([24, 1])
9 - torch.Size([24, 19]): torch.Size([24, 1])
10 - torch.Size([24, 19]): torch.Size([24, 1])
11 - torch.Size([24, 19]): torch.Size([24, 1])
12 - torch.Size([24, 19]): torch.Size([24, 1])
13 - torch.Size([24, 19]): torch.Size([24, 1])
14 - torch.Size([24, 19]): torch.Size([24, 1])
15 - torch.Size([24, 19]): torch.Size([24, 1])
16 - torch.Size([24, 19]): torch.Size([24, 1])
17 - torch.Size([24, 19]): torch

# 숙제후기
### - 느낀점
-- 범주형 norminal Data(숫자 형식이 아닌 데이터 e.g : occupation(직업), marital status(결혼 유무) 등)를 처리하기 위해 각 해당 데이터의 인덱스에만 하는 위치만 1, 나머지는 모두 0인 벡터로 변환하는 one-hot encoding에 대해 알고, one-hot encoding 이전에 eye_matrix(eye = torch.eye(classes))를 먼저 생성해두고 one-hot = eye[labels]처럼 사용하여 인덱싱만으로 one-hot 벡터를 손쉽게 얻는 방법을 실습을 통해 빠르게 깨닫을 수 있었던 것 같습니다.
-- Dataset이 한 샘플과 타깃 __len_-, __getitem__ 등 각종 interface를 이용해 제공해주고, DataLoader를 이용 batch size만큼 batch로 묶어 반복적으로 내보낸다는 것을 많은 실습 코드 예제를 통해 배웠습니다.
### - 하고싶은 말
-- 수업과정에서 이론과 실습 코드 분석이 분할되어 진행되는것이 배워가는 학부생 입장에서는 바로바로 잊지않고 어떻게 사용이되고 응용이되는지 한눈에 이해할 수 있기에 학습에 더할나위 없이 만족하고 있습니다. 감사합니다. 