# 2022161136_이재환 (전자공학과)

## ----------------------------------------------------

# _02_tensors

## ----------------------------------------------------

# a_tensor_initialization

In [1]:
import torch

## ----------------------------------------------------

In [9]:
# torch.Tensor class
t1 = torch.Tensor([1,2,3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [10]:
t1_cpu = t1.cpu()

## ----------------------------------------------------

In [11]:
# torch.tensor function
t2 = torch.tensor([1,2,3], device = 'cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [12]:
t2_cpu = t2.cpu()

## ----------------------------------------------------

In [14]:
a1 = torch.tensor(1)     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [17]:
a2 = torch.tensor([1])   # shape : torch.Size([1]), ndim(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [20]:
a3 = torch.tensor([1,2,3,4,5])  # shape : torch.Size([5]), ndim(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [22]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])  # shape : torch.Size[5, 1], ndim(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [23]:
a5 = torch.tensor([  # shape : torch.Size[3,2], ndim(=rank) : 2
    [1,2],
    [3,4],
    [5,6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [27]:
a6 = torch.tensor([  # shape : torch.Size[3,2,1], ndim(=rank) : 3
    [[1],[2]],
    [[3],[4]],
    [[5],[6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [28]:
a7 = torch.tensor([  # shape : torch.Size[3,1,2,1], ndim(=rank) : 4
    [[[1],[2]]],
    [[[3],[4]]],
    [[[5],[6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [29]:
a8 = torch.tensor([  # shape : torch.Size[3,1,2,3], ndim(=rank) : 4
    [[[1,2,3],[2,3,4]]],
    [[[3,1,1],[4,4,5]]],
    [[[5,6,2],[6,3,1]]]
])
print(a8.shape,a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [30]:
a9 = torch.tensor([  # shape : torch.Size[3,1,2,3,1], ndim(=rank) : 5
    [[[[1],[2],[3]],[[2],[3],[4]]]],
    [[[[3],[1],[1]],[[4],[4],[5]]]],
    [[[[5],[6],[2]],[[6],[3],[1]]]]
])
print(a9.shape,a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [31]:
a10 = torch.tensor([  # shape : torch.Size[4,5], ndim(=rank) : 2
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [32]:
# 이전 예제와 변수명이 같기에 일부러 다른 변수명을 사용함
a11 = torch.tensor([  # shape : torch.Size[4,1,5], ndim(=rank) : 3
    [[1,2,3,4,5]],
    [[1,2,3,4,5]],
    [[1,2,3,4,5]],
    [[1,2,3,4,5]],
])
print(a11.shape, a11.ndim)

torch.Size([4, 1, 5]) 3


In [33]:
a12 = torch.tensor([  # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1,2,3], [4,5]]],
    [[[1,2,3], [4,5]]],
    [[[1,2,3], [4,5]]],
    [[[1,2,3], [4,5]]],
])
print(a12.shape, a12.ndim)

ValueError: expected sequence of length 3 at dim 3 (got 2)

###### 3번째 dim에서 tensor의 Size가 3으로 통일되게 구성되어야하지만 Size가 3과2, 즉 두개의 Size로 구성되어있어 ValueError가 발생하였음

## ----------------------------------------------------

# b_tensor_initialization_copy

In [3]:
import torch
import numpy as np

In [6]:
l1 = [1,2,3]
t1 = torch.Tensor(l1)

In [5]:
l2 = [1,2,3]
t2 = torch.tensor(l2)

In [7]:
l3 = [1,2,3]
t3 = torch.as_tensor(l3)

In [8]:
l1[0] = 100
l2[0] = 100
l3[0] = 100

In [9]:
print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


## ----------------------------------------------------

In [10]:
l4 = np.array([1,2,3])
t4 = torch.Tensor(l4)

In [11]:
l5 = np.array([1,2,3])
t5 = torch.tensor(l5)

In [12]:
l6 = np.array([1,2,3])
t6 = torch.as_tensor(l6)

In [13]:
l4[0] = 100
l5[0] = 100
l6[0] = 100

In [15]:
print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


## ----------------------------------------------------

# c_initialization_constant_values

In [2]:
import torch

In [3]:
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [4]:
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [19]:
t3 = torch.empty(size=(4,))  # 코드를 동작할때 마다 쓰레기 값들이 tensor안에 들어가는 것을 확인함.
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([3.5873e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([0.0000e+00, 1.8980e+01, 1.1219e-05, 0.0000e+00])


##### 학습: torch.empty_like(input=t3)는 input 텐서(t3)의 각종 특징(shape, dtype, etc)을 동일하게 가지는 새로운 텐서를 생성하는 함수이다.

In [21]:
t4 = torch.eye(n=3) # 단위행렬을 만드는 함수
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## ----------------------------------------------------

# d_tensor_initialization_random_values

In [23]:
import torch

In [33]:
t1 = torch.randint(low=10, high= 20, size=(1,2)) # random int, low : inclusive, high : exclusive [low,high)
print(t1)

tensor([[11, 15]])


In [40]:
t2 = torch.rand(size=(1, 3)) # filed with float values ranging between 0 and 1 from a uniform distribution
print(t2)

tensor([[0.5351, 0.7180, 0.6216]])


In [45]:
t3 = torch.randn(size=(1,3)) # filed with a random float numboer from a standard normal distribution(정규분포) with a mean 0 and a variance of 1
print(t3)

tensor([[0.0316, 1.0890, 0.2274]])


In [48]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3,2)) # filed with a random float number from a normal distribution whose mean and standard deviation are given
print(t4)

tensor([[ 9.4746,  9.8935],
        [ 9.2835, 10.7546],
        [10.6511,  9.1563]])


In [51]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3) # returns a one-dimensional tensor between start and end and it is equally spaced based on steops
print(t5)

tensor([0.0000, 2.5000, 5.0000])


In [54]:
t6 = torch.arange(5) # returns a one-dimensional tensor with values from the interval [start, end) taken with common difference steop beginning from start
print(t6)

tensor([0, 1, 2, 3, 4])


In [56]:
torch.manual_seed(1729) # it will set the seed of the random numbere generator to a fixed value, so that when you call for example torch.rand(2), the results will be reproducible
random1 = torch.rand(2,3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [58]:
random2 = torch.rand(2,3)
print(random2)

tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])


In [60]:
torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [61]:
random4 = torch.rand(2,3)
print(random4)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## ----------------------------------------------------

# e_tensor_type_conversion

In [62]:
import torch

In [63]:
a = torch.ones((2,3))
print(a.dtype)

torch.float32


In [65]:
b = torch.ones((2,3), dtype=torch.int16)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [67]:
c = torch.rand((2,3), dtype=torch.float64) * 20
print(c)

tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)


In [68]:
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [70]:
double_d = torch.ones(10,2,dtype=torch.double)
short_e = torch.tensor([[1,2]], dtype = torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [72]:
double_d = torch.zeros(10,2).double()
short_e = torch.ones(10,2).short()

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [73]:
double_d = torch.zeros(10,2).to(torch.double)
short_e = torch.ones(10,2).to(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [75]:
double_d = torch.zeros(10,2).type(torch.double)
short_e = torch.ones(10,2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [76]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


## ----------------------------------------------------

# f_tensor_operations

In [1]:
import torch

In [9]:
t1 = torch.ones(size=(2,3)) #size가 (2,3) 원소가 1인 tensor 생성
t2 = torch.ones(size=(2,3))
t3 = torch.add(t1,t2) # 원소별 덧셈 기능을 함.
t4 = t1 + t2 # torch.add 함수와 동일기능
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [10]:
t5 = torch.sub(t1,t2) # 원소별 뺄셈 기능을 함.
t6 = t1 - t2 # torch.sub 함수와 동일 기능.
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
t7 = torch.mul(t1,t2) # 원소별 곱셈 기능을 함.
t8 = t1 * t2 # torch.mul 함수와 같은 기능을 함.
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
t9 = torch.div(t1,t2) # 원소별 나눗셈 기능을 함.
t10 = t1 / t2 # torch.div()와 같은 기능을 함.
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## ----------------------------------------------------

# g_tensor_operations_mm

In [2]:
import torch

In [5]:
t1 = torch.dot(  # 백터 내적을 연산하는 함수 [2,3] * [2,1] = (2*2) + (3*1) = 4 + 3 = 7
    torch.tensor([2,3]), torch.tensor([2,1])
)
print(t1, t1.size()) # 결과: 스칼라 값 tensor(7) torch.Size([])

tensor(7) torch.Size([])


In [6]:
t2 = torch.randn(2,3)
t3 = torch.randn(3,2)
t4 = torch.mm(t2, t3) # torch.mm : 행렬 곱을 연산하는 함수  A : (m * n), B : (a * b)일때 C의 사이즈는 (m * b) 이다.
print(t4, t4.size())

tensor([[-3.6733,  0.4776],
        [ 0.1866,  0.3615]]) torch.Size([2, 2])


In [15]:
t5 = torch.randn(10,3,4)
t6 = torch.randn(10,4,5)
#print(t5, t5.size())
#print(t6, t5.size())
t7 = torch.bmm(t5,t6) # torch.bmm은 3차원 텐서를 받아서, 텐서마다 행렬곱을 수행하는 함수.
print(t7.size()) # 즉 10개의 행렬곱을 한꺼번에 수행하는 함수이다.

torch.Size([10, 3, 5])


## ----------------------------------------------------

# h_tensor_operations_matmul

In [2]:
import torch

In [4]:
#vector x vector: dot product -> 벡터 x 벡터 : 내적(dot product)
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1,t2).size())  # matmul은 입력 차원에 따라 dot/mm/bmm 을 자동으로 처리.

torch.Size([])


In [6]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3,4)
t4 = torch.randn(4)
print(torch.matmul(t3,t4).size())

torch.Size([3])


In [24]:
# batched matrix x vector: broadcasted bot
t5 : torch.randn(10,3,4)
t6 : torch.randn(4)
print(torch.matmul(t5,t6).size())

torch.Size([10, 3, 5])


In [25]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10,3,4)
t8 = torch.randn(10,4,5)
print(torch.matmul(t7,t8).size())

torch.Size([10, 3, 5])


In [26]:
# batched matrix x matrix: bmm
t9 = torch.randn(10,3,4)
t10 = torch.randn(4,5)
print(torch.matmul(t9,t10).size())

torch.Size([10, 3, 5])


## ----------------------------------------------------

# i_tensor_broadcasting

In [1]:
import torch

In [2]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


In [5]:
t3 = torch.tensor([[0,1], [2,4],[10,10]])
t4 = torch.tensor([4,5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [7]:
t5 = torch.tensor([[1.,2.],[3.,4.]])
print(t5 + 2.0) # t5.add(2.0)
print(t5 - 2.0) # t5.sub(2.0)
print(t5 * 2.0) # t5.mul(2.0)
print(t5 / 2.0) # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [8]:
def normalize(x):
    return x / 255

In [9]:
t6 = torch.randn(3,28,28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [26]:
t7 = torch.tensor([[1,2],[0,3]]) # torch.Size([2, 2])
#print(t7.size())
t8 = torch.tensor([[3,1]]) # torch.Size([1,2])
#print(t8.size())
t9 = torch.tensor([[5],[2]]) # torch.Size([2, 1])
#print(t9.size())
t10 = torch.tensor([7]) # torch.Size([1])
#print(t10.size())
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [29]:
t11 = torch.ones(4,3,2)
t12 = t11 * torch.rand(3,2) # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape) 

torch.Size([4, 3, 2])


In [30]:
t13 = torch.ones(4,3,2)
t14 = t13 * torch.rand(3,1) # 3rd dim = 1, 2nd dim is identical to t13
print(t13.shape)

torch.Size([4, 3, 2])


In [31]:
t15 = torch.ones(4,3,2)
t16 = t15 * torch.rand(1,2) # 3rd dims is identical to t15, 2nd dim is 1
print(t16.shape)

torch.Size([4, 3, 2])


In [34]:
t17 = torch.ones(5,3,4,1)
t18 = torch.rand(3,1,1) # 2nd dims is identical to t17, 3rd and 4th dims are 1
print((t17+t18).size())

torch.Size([5, 3, 4, 1])


In [37]:
t19 = torch.empty(5,1,4,1)
t20 = torch.empty(3,1,1)
print((t19+t20).size()) # torch.Size([5,3,4,1])

torch.Size([5, 3, 4, 1])


In [39]:
t21 = torch.empty(1)
t22 = torch.empty(3,1,7)
print((t21+t22).size()) # torch.Size([3,1,7])

torch.Size([3, 1, 7])


In [41]:
t23 = torch.ones(3,3,3)
t24 = torch.ones(3,1,3)
print((t23 + t24).size()) # torch.Size([3,3,3])

torch.Size([3, 3, 3])


In [42]:
t25 = torch.empty(5,2,4,1)
t26 = torch.empty(3,1,1)
print((t25 + t26).size())

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [45]:
t27 = torch.ones(4) * 5
print(t7)

tensor([[1, 2],
        [0, 3]])


In [46]:
t28 = torch.pow(t27,2)
print(t28)

tensor([25., 25., 25., 25.])


In [47]:
exp = torch.arange(1.,5.)
a = torch.arange(1.,5.)
t29 = torch.pow(a,exp)
print(t29)

tensor([  1.,   4.,  27., 256.])


## ----------------------------------------------------

# j_tensor_indexing_slicing

In [49]:
import torch

In [50]:
x = torch.tensor(
    [[0,1,2,3,4],
     [5,6,7,8,9],
     [10,11,12,13,14]]
)

In [54]:
print(x[1])
print(x[:,1])
print(x[1,2])
print(x[:,-1])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [56]:
print(x[1:])
print(x[1:,3:])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [57]:
y = torch.zeros((6,6))
y[1:4, 2] = 1
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [58]:
print(y[1:4, 1:4])

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [62]:
z = torch.tensor(
    [[1,2,3,4],
     [2,3,4,5],
     [5,6,7,8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:,1:])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [63]:
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## ----------------------------------------------------

# k_tensor_reshaping

In [1]:
import torch

In [2]:
t1 = torch.tensor([[1,2,3], [4,5,6]])
t2 = t1.view(3,2) # Shape becomes (3, 2)
t3 = t1.reshape(1,6) # Shape becomes (1, 6)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [3]:
t4 = torch.arange(8).view(2,4) # Shape becomes (2, 4)
t5 = torch.arange(6).view(2,3) # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [4]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])
print(t6.shape)

torch.Size([1, 3, 1])


In [5]:
# Remove all dimensions of size 1
t7 = t6.squeeze() # Shape becomes (3,)
print (t7.shape)

torch.Size([3])


In [6]:
# Remove dimension at position 0
t8 = t6.squeeze(0) # Shape becomes (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [7]:
# Original tensor with shape (3,)
t9 = torch.tensor([1,2,3])
print(t9.shape)

torch.Size([3])


In [8]:
# Add a new dimension at position 1
t10 = t9.unsqueeze(1)
print(t10)

tensor([[1],
        [2],
        [3]])


In [9]:
t11 = torch.tensor(
    [[1,2,3],
     [4,5,6]]
)
t12 = t11.unsqueeze(1) # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [12]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1,2,3], [4,5,6]])
print(t13.shape)

torch.Size([2, 3])


In [14]:
# Flatten the tensor
t14 = t13.flatten() # Shape becomes (6,)
print(t14)
print(t14.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


In [16]:
# Original tensor with shpae (2, 2, 2)
t15 = torch.tensor([[[1,2],
                     [3,4]],
                     [[5,6],
                      [7,8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [20]:
t18 = torch.randn(2, 3, 5)
print(t18.shape) # >>> torch.Size([2,3,5])
print(torch.permute(t18, (2,0,1)).size()) # >> torch.Size([5,2,3])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [21]:
# Original tensor wirh shape (2,3)
t19 = torch.tensor([[1,2,3],[4,5,6]])

In [22]:
# Permute the dimensions
t20 = torch.permute(t19, dims=(0,1)) # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1,0)) # Shape becomes (3, 2)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [23]:
# Transpose the tensor
t22 = torch.transpose(t19, 0, 1) # Shape becomes (3, 2)
print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [24]:
t23 = torch.t(t19) # Shape becomes (3, 2)
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## ----------------------------------------------------

# l_tensor_concat

In [26]:
import torch

In [31]:
t1 = torch.zeros([2,1,3])
t2 = torch.zeros([2,3,3])
t3 = torch.zeros([2,2,3])

# print(t1)
# print(t2)
# print(t3)

In [32]:
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


In [33]:
t5 = torch.arange(0,3) # tensor([0,1,2])
t6 = torch.arange(3,8) # tensor([3,4,5,6,7,8])

In [35]:
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape) # >> torch.Size([8])
print(t7) # >> tensor([0,1,2,3,4,5,6,7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [38]:
t8 = torch.arange(0,6).reshape(2,3) # torch.Size([2,3])
t9 = torch.arange(6,12).reshape(2,3) # torch.Size([2,3])

# print(t8.shape)
# print(t9.shape)

In [41]:
# 2차원 텐서간 병합
t10 = torch.cat((t8,t9), dim=0)
print(t10.size()) # >> torch.Size([4,3])
print(t10) 
# >> tensor([[0, 1, 2],
#            [3, 4, 5],
#            [6, 7, 8],
#            [9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [42]:
t11 = torch.cat((t8, t9), dim = 1)
print(t11.size()) # >> torch.Size([2,6])
print(t11)
# >> tensor([[0, 1, 2, 6, 7, 8],
#            [3, 4, 5, 9, 10, 11]])

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [44]:
t12 = torch.arange(0,6).reshape(2, 3) # torch.Sizee([2,3])
t13 = torch.arange(6, 12).reshape(2, 3) # torch.Size([2,3])
t14 = torch.arange(12, 18).reshape(2, 3) # torch.Size([2,3])

# print(t12)
# print(t13)
# print(t14)

In [45]:
t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size()) # >>> torch.Size([6,3])
print(t15)
# tensor([[ 0,  1,  2],
        # [ 3,  4,  5],
        # [ 6,  7,  8],
        # [ 9, 10, 11],
        # [12, 13, 14],
        # [15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [47]:
t16 = torch.cat((t12, t13, t14), dim = 1)
print(t16.size()) # >> torch.Size([2,9])
print(t16)
# tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#         [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [53]:
t17 = torch.arange(0, 6).reshape(1,2,3)
t18 = torch.arange(6, 12).reshape(1,2,3)
print(t17)
print(t18)

tensor([[[0, 1, 2],
         [3, 4, 5]]])
tensor([[[ 6,  7,  8],
         [ 9, 10, 11]]])


In [50]:
t19 = torch.cat((t17,t18), dim=0)
print(t19.size()) # >>> torch.Size([2,2,3])
print(t19)
# tensor([[[ 0,  1,  2],
#          [ 3,  4,  5]],

#         [[ 6,  7,  8],
#          [ 9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [54]:
t20 = torch.cat((t17, t18), dim=1)
print(t20.size()) # >> torch.Size([1,4,3])
print(t20)
# tensor([[[ 0,  1,  2],
#          [ 3,  4,  5],
#          [ 6,  7,  8],
#          [ 9, 10, 11]]])

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


In [56]:
t21 = torch.cat((t17, t18), dim=2)
print(t21.size()) # >>> torch.Size([1,2,6])
print(t21)

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


## ----------------------------------------------------

# m_tensor_stacking

In [1]:
import torch

In [58]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9], [10,11,12]])

t3 = torch.stack([t1,t2], dim = 0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [59]:
t5 = torch.stack([t1,t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [60]:
t7 = torch.stack([t1,t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [62]:
t9 = torch.arange(0,3) # tensor([0,1,2])
t10 = torch.arange(3,6) # tensor([3,4,5])

print(t9.size(), t10.size()) # >> torch.Size([3]) torch.Size([3])

torch.Size([3]) torch.Size([3])


In [64]:
t11 = torch.stack((t9,t10), dim=0)
print(t11.size()) # >>> torch.Size([2,3])
print(t11)
# tensor([[0, 1, 2],
#         [3, 4, 5]])

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [77]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12)) # >> True

True


In [74]:
t13 = torch.stack((t9,t10), dim=1)
print(t13.size()) # >>> torch.Size([3,2])
print(t13)
# tensor([[0, 3],
#         [1, 4],
#         [2, 5]])

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [76]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14)) # >> True

True


## ----------------------------------------------------

# n_tensor_vstack_hstack

In [2]:
import torch

In [4]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.vstack((t1,t2))
print(t3)
# >> 
# tensor([[1, 2, 3],
#         [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
t4 = torch.tensor([[1],[2],[3]])
t5 = torch.tensor([[4],[5],[6]])
t6 = torch.vstack((t4,t5))
print(t6)
# >>
# tensor([[1],
#         [2],
#         [3],
#         [4],
#         [5],
#         [6]])

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [10]:
t7 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(t7)
# >>
# tensor([[[ 1,  2,  3],
#          [ 4,  5,  6]],

#         [[ 7,  8,  9],
#          [10, 11, 12]]])
print(t7.shape) # >> torch.Size([2, 2, 3])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


In [12]:
t8 = torch.tensor([
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24]]
])
print(t8.shape) # >> torch.Size([2,2,3])

torch.Size([2, 2, 3])


In [16]:
t9 = torch.vstack((t7,t8))
print(t9.shape)
print(t9)

torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [18]:
t10 = torch.tensor([1,2,3])
t11 = torch.tensor([4,5,6])
t12 = torch.hstack((t10,t11))
print(t12) # >> tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [22]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>
# tensor([[1, 4],
#         [2, 5],
#         [3, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [24]:
t16 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(t16.shape) # >> torch.Size([2, 2, 3])

torch.Size([2, 2, 3])


In [26]:
t17 = torch.tensor([
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24]]
])
print(t17.shape) # >> torch.Size([2,2,3])

torch.Size([2, 2, 3])


In [28]:
t18 = torch.hstack((t16,t17))
print(t18.shape) # >> torch.Size([2, 4, 3])
print(t18)
# >>
# tensor([[[ 1,  2,  3],
#          [ 4,  5,  6],
#          [13, 14, 15],
#          [16, 17, 18]],

#         [[ 7,  8,  9],
#          [10, 11, 12],
#          [19, 20, 21],
#          [22, 23, 24]]])

torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제후기
### - 느낀점
-- 수집하는 데이터들을 결국 tensor로 변환하여 처리해야하는 만큼 기본이되는 tensor연산에 대해 알아볼수 있어서 좋았습니다.
-- 특히 tensor에서 cat, stack연산을 공부할때 쉽게 와닿지 않았는데 예제를 많이 작성하여 shape를 일일히 찍어봄으로써 점차 감각을 익힐 수 있었던 것 같습니다.
### - 하고싶은 말
-- 아직은 tensor의 양 즉 엄청 방대한 양의 데이터를 처리해보지 않아 pytorch와 numpy의 차이점인 cuda 즉 gpu 연산에 대해서 얼마나 차이가 많이 나는지를 체감해 볼 기회가 적었던 것같아서 조금 아쉽습니다.